# Generated by Django 5.1.7 on 2025-03-17 15:31

import blog.models
import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'gif', 'webp')), core.utils.validate_file_size]),
        ),
    ]
