# Generated by Django 5.1.7 on 2025-03-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_upvote'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('post', 'profile')},
        ),
    ]
