# Generated by Django 5.1.7 on 2025-03-17 16:27

import core.utils
import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='defaults/def.png', upload_to=profiles.models.upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'gif', 'webp')), core.utils.validate_file_size])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('-created',),
            },
        ),
    ]
